#spring:
#  security:
#    oauth2:
#      client:
#        provider:
#          azure-ad:
#            authorization-uri: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
#            token-uri: https://login.microsoftonline.com/common/oauth2/v2.0/token
#            jwk-set-uri: https://login.microsoftonline.com/common/discovery/v2.0/keys
#        registration:
#          azure-client:
#            provider: azure-ad
##            client-id: cf4e59eb-7ab0-484c-a96b-7c608cf006d8 // mail huynguyen-lang
##            client-secret: JE58Q~FFIof_LQaYV6NckCWYJXJfNfA.lRqk4b7o // client-secret huynguyen-lang
#            authorization-grant-type: authorization_code
#            redirect-uri: '{baseUrl}/login/oauth2/code/{registrationId}'
#            scope: openid,profile,https://graph.microsoft.com/Mail.Read, https://graph.microsoft.com/User.Read
#
#
#
#
#server:
#  forward-headers-strategy: native
#
#
